"use client";

import { useState } from "react";

type Workflow = {
  id: string;
  name: string;
  description: string;
  category: string;
  steps: { name: string; agent: string }[];
};

type BriefData = {
  projectName?: string;
  projectType?: string;
  goals?: string;
  timeline?: string;
  budget?: string;
  references?: string;
  introduction?: string;
  conclusion?: string;
};

type ExportFormat = "claude" | "runbook" | "context";

const ExportBrief = ({ workflow, briefData }: { workflow: Workflow | null; briefData: BriefData }) => {
  const [showMenu, setShowMenu] = useState(false);
  const [copied, setCopied] = useState<string | null>(null);
  const timestamp = new Date().toISOString().split("T")[0];
  const projectName = briefData.projectName || workflow?.name || "Untitled Project";
  const slug = projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

  const gen = (format: ExportFormat): string => {
    const wfName = workflow?.name || "Custom Brief";
    const wfCat = workflow?.category || "N/A";
    const pType = briefData.projectType || workflow?.category || "Design";
    const pipeline = workflow ? workflow.steps.map(s => s.agent.toUpperCase()).join(" \u2192 ") : "";
    const steps = workflow ? workflow.steps.map((s, i) => `${i + 1}. **${s.name}** \u2192 \`${s.agent.toUpperCase()}\``).join("\n") : "";
    const stepsRunbook = workflow ? workflow.steps.map((s, i) =>
      `### Step ${i + 1}: ${s.name}\n- **Agent:** ${s.agent.toUpperCase()}\n- **Status:** \u2B1C Pending\n- **Output:** \`/outputs/${slug}/step-${i + 1}/\`\n`
    ).join("\n") : "No workflow steps defined.\n";

    if (format === "claude") return `# CLAUDE.md \u2014 ${projectName}

> Auto-generated by Inferis Studio on ${timestamp}
> Workflow: ${wfName} (${wfCat})

## Project Overview

**Name:** ${projectName}
**Type:** ${pType}
**Generated:** ${timestamp}
${workflow ? `**Workflow:** ${workflow.name} \u2014 ${workflow.description}\n**Agent Pipeline:** ${pipeline}` : ""}

## Goals

${briefData.goals || "Define project goals."}

## Scope & Constraints

${briefData.introduction || "Project scope to be defined."}

## Timeline

${briefData.timeline || "Timeline to be determined."}

## Budget

${briefData.budget || "Budget to be confirmed."}

## References & Inspiration

${briefData.references || "No references provided."}

${workflow ? `## Workflow Steps\n\n${steps}\n` : ""}
## Agent Instructions

When working on this project:
- Follow the goals and constraints above
- Reference the timeline for delivery expectations
- Use the workflow steps as your execution order
- Escalate creative decisions to the human lead
- Output deliverables to \`/outputs/${slug}/\`

## Notes

${briefData.conclusion || "No additional notes."}

---
*Exported from Inferis Studio \u00B7 ryujin.inferis.app*`;

    if (format === "runbook") return `# RUNBOOK: ${projectName}

| Field | Value |
|-------|-------|
| Project | ${projectName} |
| Type | ${pType} |
| Workflow | ${wfName} |
| Created | ${timestamp} |
| Status | Draft |

---

## 1. Brief

${briefData.introduction || "Project brief pending."}

## 2. Goals

${briefData.goals || "Goals pending."}

## 3. Execution Steps

${stepsRunbook}
## 4. Timeline

${briefData.timeline || "TBD"}

## 5. Budget

${briefData.budget || "TBD"}

## 6. References

${briefData.references || "None"}

## 7. Sign-off

- [ ] Brief approved
- [ ] Workflow validated
- [ ] Deliverables reviewed
- [ ] Client sign-off

---
*Generated by Inferis Studio \u00B7 ${timestamp}*`;

    // context format — XML tags for pasting into Claude
    return `<project_context>
<name>${projectName}</name>
<type>${pType}</type>
<workflow>${wfName}</workflow>
${workflow ? `<pipeline>${pipeline}</pipeline>` : ""}
<created>${timestamp}</created>

<brief>${briefData.introduction || "No brief content."}</brief>
<goals>${briefData.goals || "No goals defined."}</goals>
<timeline>${briefData.timeline || "No timeline."}</timeline>
<budget>${briefData.budget || "No budget."}</budget>
<references>${briefData.references || "None."}</references>
${workflow ? `<steps>\n${workflow.steps.map((s, i) => `<step n="${i + 1}" agent="${s.agent}">${s.name}</step>`).join("\n")}\n</steps>` : ""}
<notes>${briefData.conclusion || "No additional notes."}</notes>
</project_context>`;
  };

  const downloadFile = (format: ExportFormat) => {
    const content = gen(format);
    const filename = format === "claude" ? "CLAUDE.md" : format === "runbook" ? `${slug}-runbook.md` : `${slug}-context.md`;
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = filename;
    document.body.appendChild(a); a.click();
    document.body.removeChild(a); URL.revokeObjectURL(url);
    setShowMenu(false);
  };

  const copyToClipboard = (format: ExportFormat) => {
    navigator.clipboard.writeText(gen(format)).then(() => {
      setCopied(format);
      setTimeout(() => setCopied(null), 2000);
    });
  };

  return (
    <div className="relative">
      <button onClick={() => setShowMenu(!showMenu)}
        className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-b-dark1 text-t-light text-button hover:bg-b-dark2 transition-all active:scale-[0.98] shadow-hover">
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" className="shrink-0">
          <path d="M8 1v10M4 7l4 4 4-4M2 13h12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
        Export
      </button>

      {showMenu && (<>
        <div className="fixed inset-0 z-40" onClick={() => setShowMenu(false)} />
        <div className="absolute bottom-full mb-2 right-0 w-72 bg-b-surface2 border border-stroke2 rounded-2xl shadow-hover z-50 overflow-hidden">
          <div className="px-4 py-3 border-b border-stroke-subtle">
            <div className="text-heading font-medium text-t-primary">Export Brief</div>
            <div className="text-small text-t-tertiary mt-0.5">Choose format for Claude Code or docs</div>
          </div>
          <div className="px-3 py-2 border-b border-stroke-subtle">
            <div className="flex items-center gap-2 mb-1.5">
              <span className="px-1.5 py-0.5 rounded text-[9px] font-bold tracking-wider bg-primary2/10 text-primary2">RECOMMENDED</span>
            </div>
            <div className="flex gap-1.5">
              <button onClick={() => downloadFile("claude")} className="flex-1 flex items-center justify-center gap-1.5 px-3 py-2 rounded-lg bg-primary2/10 border border-primary2/20 text-[12px] font-medium text-primary2 hover:bg-primary2/20 transition-all">
                {"\u2193"} CLAUDE.md
              </button>
              <button onClick={() => copyToClipboard("claude")} className="px-3 py-2 rounded-lg border border-stroke-subtle text-[12px] text-t-secondary hover:text-t-primary hover:border-stroke-highlight transition-all">
                {copied === "claude" ? "\u2713 Copied" : "Copy"}
              </button>
            </div>
            <div className="text-[10px] text-t-tertiary mt-1.5">Drop into your project root for Claude Code context</div>
          </div>
          <div className="px-3 py-2 border-b border-stroke-subtle">
            <div className="flex gap-1.5">
              <button onClick={() => downloadFile("runbook")} className="flex-1 flex items-center justify-center gap-1.5 px-3 py-2 rounded-lg border border-stroke-subtle text-[12px] font-medium text-t-secondary hover:text-t-primary hover:border-stroke-highlight transition-all">
                {"\u2193"} Runbook .md
              </button>
              <button onClick={() => copyToClipboard("runbook")} className="px-3 py-2 rounded-lg border border-stroke-subtle text-[12px] text-t-secondary hover:text-t-primary hover:border-stroke-highlight transition-all">
                {copied === "runbook" ? "\u2713 Copied" : "Copy"}
              </button>
            </div>
            <div className="text-[10px] text-t-tertiary mt-1.5">Structured execution plan with step checklists</div>
          </div>
          <div className="px-3 py-2">
            <div className="flex gap-1.5">
              <button onClick={() => downloadFile("context")} className="flex-1 flex items-center justify-center gap-1.5 px-3 py-2 rounded-lg border border-stroke-subtle text-[12px] font-medium text-t-secondary hover:text-t-primary hover:border-stroke-highlight transition-all">
                {"\u2193"} Context .md
              </button>
              <button onClick={() => copyToClipboard("context")} className="px-3 py-2 rounded-lg border border-stroke-subtle text-[12px] text-t-secondary hover:text-t-primary hover:border-stroke-highlight transition-all">
                {copied === "context" ? "\u2713 Copied" : "Copy"}
              </button>
            </div>
            <div className="text-[10px] text-t-tertiary mt-1.5">XML-tagged context block — paste directly into a Claude prompt</div>
          </div>
        </div>
      </>)}
    </div>
  );
};

export default ExportBrief;
